### ISSUE TITLE
Case tab not loading

### ISSUE THREAD

**Issue by Stoob** [twomice/civicrm-caseenddate#1]
I was unable to find any log messages but this "Network Error" appears when the Case tab is loaded in a Contact.  Disabling the extension makes the error go away.

![cases-tab](https://user-images.githubusercontent.com/1683473/68891854-8ad1e180-06d6-11ea-8907-fbf18fb3a90e.png)

**Comment by twomice** [comment]
Thanks for the report @Stoob . This is fixed in master, in tag v1.1.
